/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package event.management;

import javax.swing.JOptionPane;

/**
 *
 * @author arushi shetty
 */
public class homepage extends javax.swing.JFrame {

    /**
     * Creates new form homepage
     */
    public homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventsHome = new javax.swing.JButton();
        LoginHOme = new javax.swing.JButton();
        AboutUsHome = new javax.swing.JButton();
        GalleryHome = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        HomepageImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        setMaximumSize(new java.awt.Dimension(1155, 649));
        setMinimumSize(new java.awt.Dimension(1155, 649));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eventsHome.setBackground(new java.awt.Color(255, 255, 255));
        eventsHome.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        eventsHome.setForeground(new java.awt.Color(0, 51, 255));
        eventsHome.setText("Events");
        eventsHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventsHomeActionPerformed(evt);
            }
        });
        getContentPane().add(eventsHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 130, -1));

        LoginHOme.setBackground(new java.awt.Color(255, 255, 255));
        LoginHOme.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LoginHOme.setForeground(new java.awt.Color(0, 102, 255));
        LoginHOme.setText("Login");
        LoginHOme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginHOmeActionPerformed(evt);
            }
        });
        getContentPane().add(LoginHOme, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 120, -1));

        AboutUsHome.setBackground(new java.awt.Color(255, 255, 255));
        AboutUsHome.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        AboutUsHome.setForeground(new java.awt.Color(0, 102, 255));
        AboutUsHome.setText("About Us");
        AboutUsHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsHomeActionPerformed(evt);
            }
        });
        getContentPane().add(AboutUsHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 130, -1));

        GalleryHome.setBackground(new java.awt.Color(255, 255, 255));
        GalleryHome.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        GalleryHome.setForeground(new java.awt.Color(0, 102, 255));
        GalleryHome.setText("Rate Events");
        GalleryHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GalleryHomeActionPerformed(evt);
            }
        });
        getContentPane().add(GalleryHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 130, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit small.png"))); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 130, 30));

        HomepageImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homepage.png"))); // NOI18N
        HomepageImage.setText("jLabel1");
        HomepageImage.setMaximumSize(new java.awt.Dimension(1155, 649));
        HomepageImage.setMinimumSize(new java.awt.Dimension(1155, 649));
        HomepageImage.setPreferredSize(new java.awt.Dimension(1155, 649));
        getContentPane().add(HomepageImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eventsHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventsHomeActionPerformed
        // TODO add your handling code here:
       new eventHomepage().setVisible(true);
       dispose();
       
    }//GEN-LAST:event_eventsHomeActionPerformed

    private void AboutUsHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsHomeActionPerformed
        // TODO add your handling code here:
        new aboutus().setVisible(true);
            dispose();
    }//GEN-LAST:event_AboutUsHomeActionPerformed

    private void LoginHOmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginHOmeActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
            dispose();
        
    }//GEN-LAST:event_LoginHOmeActionPerformed

    private void GalleryHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GalleryHomeActionPerformed
        // TODO add your handling code here:
        new ratings().setVisible(true);
        dispose();
    }//GEN-LAST:event_GalleryHomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         int a=JOptionPane.showConfirmDialog(null,"Do you really want to close the application?","Select",JOptionPane.YES_NO_OPTION);
        if (a==0)
        {
            System.exit(0);
        }
            
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutUsHome;
    private javax.swing.JButton GalleryHome;
    private javax.swing.JLabel HomepageImage;
    private javax.swing.JButton LoginHOme;
    private javax.swing.JButton eventsHome;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
