/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package event.management;
//import javax. swing. *;

import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
//import java.util.Properties;

/**
 *
 * @author arushi shetty
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //user_role take as string
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        UsernameLogin = new javax.swing.JLabel();
        PasswordLogin = new javax.swing.JLabel();
        UsernameTextL = new javax.swing.JTextField();
        SignupLogin = new javax.swing.JButton();
        NameLo = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1155, 649));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsernameLogin.setBackground(new java.awt.Color(0, 51, 204));
        UsernameLogin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        UsernameLogin.setForeground(new java.awt.Color(0, 0, 204));
        UsernameLogin.setText("Username");
        getContentPane().add(UsernameLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 100, 40));

        PasswordLogin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PasswordLogin.setForeground(new java.awt.Color(0, 51, 204));
        PasswordLogin.setText("Password");
        getContentPane().add(PasswordLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 120, 30));

        UsernameTextL.setBackground(new java.awt.Color(0, 51, 204));
        UsernameTextL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        UsernameTextL.setForeground(new java.awt.Color(255, 255, 255));
        UsernameTextL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextLActionPerformed(evt);
            }
        });
        getContentPane().add(UsernameTextL, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 300, 30));

        SignupLogin.setBackground(new java.awt.Color(0, 51, 204));
        SignupLogin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SignupLogin.setText("SignUp");
        SignupLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupLoginActionPerformed(evt);
            }
        });
        getContentPane().add(SignupLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, -1));

        NameLo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        NameLo.setForeground(new java.awt.Color(0, 51, 204));
        NameLo.setText("New?");
        getContentPane().add(NameLo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        jCheckBox1.setBackground(new java.awt.Color(0, 0, 204));
        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 300, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(225, 225, 225));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 405, 80, 30));

        jButton2.setBackground(new java.awt.Color(0, 0, 153));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(225, 225, 225));
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 405, 80, 30));

        jPasswordField1.setBackground(new java.awt.Color(51, 0, 204));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 319, 300, 30));

        jButton3.setBackground(new java.awt.Color(0, 0, 153));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(225, 225, 225));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 80, 30));

        jButton4.setBackground(new java.awt.Color(0, 0, 153));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton4.setForeground(new java.awt.Color(225, 225, 225));
        jButton4.setText("Edit Role");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 80, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LoginPage.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameTextLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextLActionPerformed

    private void SignupLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupLoginActionPerformed
        // TODO add your handling code here:
        new Signup().setVisible(true);
        dispose();
    }//GEN-LAST:event_SignupLoginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (UsernameTextL.getText().equals("admin") && jPasswordField1.getText().equals("admin")) {
            new adminpage().setVisible(true);
            dispose();
        } else {
            Connection conn = null;
            try {
                String url1 = "jdbc:mysql://localhost:3306/emsdb";
                String user = "root";
                String password = "0925arushi";

                conn = DriverManager.getConnection(url1, user, password);
                if (conn != null) {
                    System.out.println("Connected to the database");
                    //  String sqli;
                    PreparedStatement ps;
                    String PASSWORD = jPasswordField1.getText();
                    String USER_NAME = UsernameTextL.getText();
                   if(PASSWORD==null || PASSWORD.isEmpty() || USER_NAME==null ||  USER_NAME.isEmpty() )
                 {
                     JOptionPane.showMessageDialog(null,"PLease fill the credentials");
                     
                    
                    
                 }
                   else{
                    ps = conn.prepareStatement("select * from emsdb.users where user_name=? and password=?");
                    ps.setString(1, USER_NAME);
                    ps.setString(2, PASSWORD);
                    ResultSet rs = ps.executeQuery();
                        
                         if (rs.next()) {

                        // JOptionPane.showMessageDialog(null,"login successful","login sucess",JOptionPane.OK_OPTION);
                        // if( == JOptionPane.OK_OPTION)
                        //System.out.print("USER_ROLE: "+rs.getString("USER_ROLE"));
                        String a = rs.getString("USER_ROLE");
                        System.out.println(a);
                        if (a.equals("Volunteer")) {
                            new userPost().setVisible(true);
                            dispose();
                        } else if (a.equals("Participant")) {
                            new userPost1().setVisible(true);
                            dispose();
                            System.out.println(a);
                            
                        } else {
                            new homepage().setVisible(true);
                            dispose();
                            
                        }


                    }else{
                              JOptionPane.showMessageDialog(null,"User Doesnt exist");

                         }
                         
               
                    //redirecting if this exists row, based on user role redirect
                    conn.close();
                }
                }
            } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(null,"User Doesnt exist");
                System.out.println("An error occurred");
                ex.printStackTrace();
            } finally {
                if (conn != null) {
                    try {
                        conn.close();
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                }
            }

    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to close the application?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()) {
            jPasswordField1.setEchoChar((char) 0);
        } else {
            jPasswordField1.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new homepage().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new updaterole().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameLo;
    private javax.swing.JLabel PasswordLogin;
    private javax.swing.JButton SignupLogin;
    private javax.swing.JLabel UsernameLogin;
    private javax.swing.JTextField UsernameTextL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
