/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package event.management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane; 
import javax.swing.table.*;

/**
 *
 * @author arushi shetty
 */
public class organiserslist extends javax.swing.JFrame {

    /**
     * Creates new form organiserslist
     */
    public organiserslist() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        OTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        oidtxt = new javax.swing.JTextField();
        onametxt = new javax.swing.JTextField();
        odepttxt = new javax.swing.JTextField();
        ophonetxt = new javax.swing.JTextField();
        evidtxt = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        dbbutton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ORG_ID", "ORG_NAME", "ORG_DEPT", "ORG_PHONE", "EVENT_ID"
            }
        ));
        OTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(OTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 640, 120));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 153));
        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 80, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 153));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 80, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Organiser ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Organiser Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Organiser Dept");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Organiser Phone");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Event ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, -1, -1));

        oidtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oidtxtActionPerformed(evt);
            }
        });
        getContentPane().add(oidtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 170, -1));
        getContentPane().add(onametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 170, -1));
        getContentPane().add(odepttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 170, -1));
        getContentPane().add(ophonetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 170, -1));

        evidtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evidtxtActionPerformed(evt);
            }
        });
        getContentPane().add(evidtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 170, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 51, 153));
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 80, -1));

        dbbutton.setBackground(new java.awt.Color(255, 255, 255));
        dbbutton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        dbbutton.setForeground(new java.awt.Color(0, 51, 153));
        dbbutton.setText("Refresh");
        dbbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(dbbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 120, 20));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 153));
        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 80, -1));

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        home.setForeground(new java.awt.Color(0, 51, 153));
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1 1 home.jpg"))); // NOI18N
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 150, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(231, 0, 51));
        jLabel9.setText("\"null,if no dept\"");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, 20));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 153));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/organisersadmin.png"))); // NOI18N
        jLabel8.setText("l");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new adminpage().setVisible(true);
            dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Connection conn = null;
         try{
             String url1 = "jdbc:mysql://localhost:3306/emsdb";
             String user = "root";
             String password = "0925arushi";
             
             conn = DriverManager.getConnection(url1, user, password);
            if (conn != null) {
                System.out.println("Connected to the database");
                String sqli;
                 String ORG_ID=oidtxt.getText();
                 String ORG_NAME=onametxt.getText();
                 String ORG_DEPT=odepttxt.getText();
                 String ORG_PHONE=ophonetxt.getText();
                 String EV_ID=evidtxt.getText();
                 PreparedStatement ps;
                 if(ORG_DEPT==null || ORG_DEPT.isEmpty() || ORG_NAME==null || ORG_NAME.isEmpty()  || ORG_PHONE==null ||  ORG_PHONE.isEmpty())
                 {
                     JOptionPane.showMessageDialog(null,"please fill all the deatils");
                      throw new IllegalArgumentException("ORG_NAME and ORG_DEPT cannot be null or empty.");
                     
                 }
                 
                 
                sqli = "Insert into emsdb.organizer values(?,?,?,?,?)";
                ps = conn.prepareStatement(sqli);
                 ps.setString(1,ORG_ID);
                 ps.setString(2,ORG_NAME);
                 ps.setString(3,ORG_DEPT);
                 ps.setString(4,ORG_PHONE);
                 ps.setString(5,EV_ID);
                  ps.execute();
               JOptionPane.showMessageDialog(null,"Organizer added");
                 conn.close();
                oidtxt.setText(null);
                onametxt.setText(null);
                   odepttxt.setText(null);
                  ophonetxt.setText(null);
                   evidtxt.setText(null);
                 
    }//GEN-LAST:event_jButton1ActionPerformed
         }
          catch (SQLException ex) {
             JOptionPane.showMessageDialog(null,"please fill ddetails properly"); 
            System.out.println("An error occurred");
            ex.printStackTrace();
        }
         finally {
            if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
}
    }
    private void evidtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evidtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_evidtxtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         Connection conn = null;
         try{
             String url1 = "jdbc:mysql://localhost:3306/emsdb";
             String user = "root";
             String password = "0925arushi";
             
             conn = DriverManager.getConnection(url1, user, password);
            if (conn != null) {
                  System.out.println("Connected to the database");
                String sqli;
                 
                 PreparedStatement ps;
                sqli = "delete from emsdb.organizer where ORG_ID='"+oidtxt.getText()+"'";
                ps = conn.prepareStatement(sqli);
                 ps.executeUpdate();
                 JOptionPane.showMessageDialog(null,"organizer deleted");
                 conn.close();
                 
               
            }
         }
          
         catch (SQLException ex) {
              JOptionPane.showMessageDialog(null,"please fill ddetails properly");
            System.out.println("An error occurred");
            ex.printStackTrace();
        }
         finally {
            if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void dbbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbbuttonActionPerformed
        // TODO add your handling code here:
         Connection conn = null;
       try{
         String url1 = "jdbc:mysql://localhost:3306/emsdb";
             String user = "root";
             String password = "0925arushi";
             
             conn = DriverManager.getConnection(url1, user, password);
            if (conn != null) {
                  System.out.println("Connected to the database");
       
         
            String Sql="Select * from emsdb.organizer";
            PreparedStatement pstmt = conn.prepareStatement(Sql);
            ResultSet rs = pstmt.executeQuery();
            DefaultTableModel model=(DefaultTableModel)OTable.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)});
            }
            }
       
       }
        catch (SQLException ex) {
             
            System.out.println("An error occurred");
            ex.printStackTrace();
        }
         finally {
            if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
       
                 }
        
    }//GEN-LAST:event_dbbuttonActionPerformed

    private void oidtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oidtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oidtxtActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         Connection conn = null;
         try{
             String url1 = "jdbc:mysql://localhost:3306/emsdb";
             String user = "root";
             String password = "0925arushi";
             
             conn = DriverManager.getConnection(url1, user, password);
            if (conn != null) {
                  System.out.println("Connected to the database");
                String sqli;
          
                String ORG_ID=oidtxt.getText();
                
                 String EVENT_ID = evidtxt.getText();
                String ORG_NAME = onametxt.getText();
                String ORG_DEPT = odepttxt.getText();
                String ORG_PHONE = ophonetxt.getText();
               if(ORG_DEPT==null || ORG_DEPT.isEmpty() || ORG_NAME==null || ORG_NAME.isEmpty()  || ORG_PHONE==null ||  ORG_PHONE.isEmpty())
                 {
                     JOptionPane.showMessageDialog(null,"please fill all the deatils");
                      throw new IllegalArgumentException("ORG_NAME and ORG_DEPT cannot be null or empty.");
                     
                 }
                PreparedStatement ps;
                sqli= "update emsdb.organizer set ORG_NAME='"+ORG_NAME+"',ORG_DEPT='"+ORG_DEPT+"',ORG_PHONE='"+ORG_PHONE+"',EVENT_ID='"+EVENT_ID+"' where ORG_ID='"+ORG_ID+"'";
                ps = conn.prepareStatement(sqli);
               
              
                
               
                ps.execute();
                JOptionPane.showMessageDialog(null,"Organizer UPDATED");
                conn.close();
                 oidtxt.setText(null);
                onametxt.setText(null);
                   odepttxt.setText(null);
                  ophonetxt.setText(null);
                   evidtxt.setText(null);
               
                
                 conn.close();
                 
               
            }
         }
          
         catch (SQLException ex) {
              JOptionPane.showMessageDialog(null,"please fill ddetails properly");
            System.out.println("An error occurred");
            ex.printStackTrace();
        }
         finally {
            if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void OTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OTableMouseClicked
        // TODO add your handling code here:
         DefaultTableModel model=(DefaultTableModel)OTable.getModel();
        int i=OTable.getSelectedRow();
       
        oidtxt.setText(model.getValueAt(i,0).toString());
        onametxt.setText(model.getValueAt(i,1).toString());
        odepttxt.setText(model.getValueAt(i,2).toString());
         ophonetxt.setText(model.getValueAt(i,3).toString());
        evidtxt.setText(model.getValueAt(i,4).toString());
    }//GEN-LAST:event_OTableMouseClicked

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        new homepage().setVisible(true);
        dispose();
    }//GEN-LAST:event_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(organiserslist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(organiserslist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(organiserslist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(organiserslist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new organiserslist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable OTable;
    private javax.swing.JButton dbbutton;
    private javax.swing.JTextField evidtxt;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField odepttxt;
    private javax.swing.JTextField oidtxt;
    private javax.swing.JTextField onametxt;
    private javax.swing.JTextField ophonetxt;
    // End of variables declaration//GEN-END:variables
}
