/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package event.management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author arushi shetty
 */
public class ratings extends javax.swing.JFrame {

    /**
     * Creates new form ratings
     */
    public ratings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        revidtxt = new javax.swing.JTextField();
        rtxt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        urusn = new javax.swing.JLabel();
        rusntxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1155, 649));
        setMinimumSize(new java.awt.Dimension(1155, 649));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 600, 110, 50));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Event_ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 90, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rate(1-5)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 80, 20));

        revidtxt.setBackground(new java.awt.Color(255, 255, 255));
        revidtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revidtxtActionPerformed(evt);
            }
        });
        getContentPane().add(revidtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 230, 30));

        rtxt.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(rtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 230, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 153));
        jButton2.setText("Refer Events");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 130, 30));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 204));
        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, -1, -1));

        urusn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        urusn.setForeground(new java.awt.Color(255, 255, 255));
        urusn.setText("Your Usn");
        getContentPane().add(urusn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 70, 20));

        rusntxt.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(rusntxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 230, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eVENT MANAGEMENT SYSTEM (1155 × 649 px) (5).png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(1155, 649));
        jLabel2.setMinimumSize(new java.awt.Dimension(1155, 649));
        jLabel2.setPreferredSize(new java.awt.Dimension(1155, 649));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new homepage().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new eventHomepage().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void revidtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revidtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_revidtxtActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
         try{
             String url1 = "jdbc:mysql://localhost:3306/emsdb";
             String user = "root";
             String password = "0925arushi";
             
             conn = DriverManager.getConnection(url1, user, password);
            if (conn != null) {
                System.out.println("Connected to the database");
                String sqli;
                String R_EV_ID=revidtxt.getText();
                
                 String STAR= rtxt.getText();
                 String R_USN=rusntxt.getText();
               
                PreparedStatement ps;
                sqli = "Insert into emsdb.rating values(?,?,?)";
                ps = conn.prepareStatement(sqli);
               
                ps.setString(1,R_EV_ID );
                ps.setString(2, STAR);
                ps.setString(3,R_USN);
              
                
               
                ps.execute();
                JOptionPane.showMessageDialog(null,"Thanyou for your feedback!");
                conn.close();
                revidtxt.setText(null);
                rtxt.setText(null);
                rusntxt.setText(null);
               
                
                
                
                
            }
         }
 
        
         catch (SQLException ex) {
              if(ex.getErrorCode()==1366)
        {
            JOptionPane.showMessageDialog(null,"please fill the details","ratings failed",2);
            
        }
               if (ex.getErrorCode() == 1452)
               {
                   JOptionPane.showMessageDialog(null,"incorrect details");
               }
               if (ex.getErrorCode() ==1062){
              JOptionPane.showMessageDialog(null,"you have already rated for this event, thankyou!");
               }
               revidtxt.setText(null);
                rtxt.setText(null);
                rusntxt.setText(null);
               
               System.out.println("An error occurred");
            ex.printStackTrace();
        }
    
         finally {
            if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
         }
    
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ratings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ratings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ratings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ratings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ratings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField revidtxt;
    private javax.swing.JTextField rtxt;
    private javax.swing.JTextField rusntxt;
    private javax.swing.JLabel urusn;
    // End of variables declaration//GEN-END:variables
}
