/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package event.management;



import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Properties;


/**
 *
 * @author arushi shetty
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameSign = new javax.swing.JLabel();
        USNsign = new javax.swing.JLabel();
        Emailsign = new javax.swing.JLabel();
        PasswordSign = new javax.swing.JLabel();
        SecuritySign = new javax.swing.JLabel();
        AnswerSign = new javax.swing.JLabel();
        Nametxt = new javax.swing.JTextField();
        usntxt = new javax.swing.JTextField();
        Emailtxt = new javax.swing.JTextField();
        SaveButSign = new javax.swing.JButton();
        ExitButSign = new javax.swing.JButton();
        LoginButSign = new javax.swing.JButton();
        passwordtxt1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        phonetxt = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1193, 649));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameSign.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NameSign.setForeground(new java.awt.Color(0, 51, 153));
        NameSign.setText("Name");
        getContentPane().add(NameSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        USNsign.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        USNsign.setForeground(new java.awt.Color(0, 51, 153));
        USNsign.setText("USN");
        getContentPane().add(USNsign, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        Emailsign.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Emailsign.setForeground(new java.awt.Color(0, 51, 153));
        Emailsign.setText("E-Mail");
        getContentPane().add(Emailsign, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        PasswordSign.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        PasswordSign.setForeground(new java.awt.Color(0, 51, 153));
        PasswordSign.setText("Password");
        getContentPane().add(PasswordSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        SecuritySign.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SecuritySign.setForeground(new java.awt.Color(0, 51, 153));
        SecuritySign.setText("Role");
        getContentPane().add(SecuritySign, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        AnswerSign.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        AnswerSign.setForeground(new java.awt.Color(0, 51, 153));
        getContentPane().add(AnswerSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, -1));

        Nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NametxtActionPerformed(evt);
            }
        });
        getContentPane().add(Nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 190, -1));
        getContentPane().add(usntxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 190, -1));
        getContentPane().add(Emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 190, -1));

        SaveButSign.setBackground(new java.awt.Color(0, 51, 153));
        SaveButSign.setForeground(new java.awt.Color(255, 255, 255));
        SaveButSign.setText("Save");
        SaveButSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButSignActionPerformed(evt);
            }
        });
        getContentPane().add(SaveButSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 83, -1));

        ExitButSign.setBackground(new java.awt.Color(0, 51, 153));
        ExitButSign.setForeground(new java.awt.Color(255, 255, 255));
        ExitButSign.setText("Exit");
        ExitButSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButSignActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 610, 60, 30));

        LoginButSign.setBackground(new java.awt.Color(0, 51, 153));
        LoginButSign.setForeground(new java.awt.Color(255, 255, 255));
        LoginButSign.setText("Login");
        LoginButSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButSignActionPerformed(evt);
            }
        });
        getContentPane().add(LoginButSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 84, -1));
        getContentPane().add(passwordtxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 190, 20));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Phone no");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(0, 51, 102));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Attendee", "Participant", "Volunteer" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 110, -1));
        getContentPane().add(phonetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 190, -1));

        jTextField2.setText("jTextField2");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 3, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(247, 13, 11));
        jLabel4.setText("no alphabets & must be \"10 digits\"");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 170, 20));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 3, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(247, 13, 11));
        jLabel5.setText(" can update this later*");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 140, 20));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 3, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(247, 13, 11));
        jLabel6.setText("must be \"@sahyadri.edu.in\"");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 140, 20));

        jLabel1.setBackground(new java.awt.Color(0, 51, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signUpF.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NametxtActionPerformed

    private void ExitButSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButSignActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Do you really want to close the application?","Select",JOptionPane.YES_NO_OPTION);
        if (a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_ExitButSignActionPerformed

    private void SaveButSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButSignActionPerformed
        // TODO add your handling code here:
        
        
        
         Connection conn = null;
         try{
             String url1 = "jdbc:mysql://localhost:3306/emsdb";
             String user = "root";
             String password = "0925arushi";
             
             conn = DriverManager.getConnection(url1, user, password);
            if (conn != null) {
                System.out.println("Connected to the database");
                String sqli;
                String PASSWORD = passwordtxt1.getText();
                String USER_EMAIL = Emailtxt.getText();
                String USER_NAME = Nametxt.getText();
                String USER_PHONE = phonetxt.getText();
                String USER_ROLE = jComboBox1.getSelectedItem().toString();
                String USN = usntxt.getText();
              
                PreparedStatement ps;
                sqli = "Insert into emsdb.users values(?,?,?,?,?,?)";
                ps = conn.prepareStatement(sqli);
                ps.setString(1, USER_NAME);
                ps.setString(2, USN);
                ps.setString(3, USER_EMAIL);
                ps.setString(4, USER_PHONE);
                ps.setString(5, PASSWORD);
                ps.setString(6, USER_ROLE);
                System.out.println(USER_NAME);
               
                
                             
               
                ps.execute();
                  JOptionPane.showMessageDialog(null,"User Saved");

                conn.close();
                passwordtxt1.setText(null);
                Emailtxt.setText(null);
                Nametxt.setText(null);
                phonetxt.setText(null);
                
                        usntxt.setText(null);
                
            
        
        
         
         
      
           
        }
         }
    
         
         catch (Exception ex) {
           
               JOptionPane.showMessageDialog(null,"Invalid!!! \nPlease fill according to the mentioned format");
                 new Signup().setVisible(true);
                    
            System.out.println("An error occurred");
            ex.printStackTrace();
        }
         
         finally{
            if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
}
         
        
    }//GEN-LAST:event_SaveButSignActionPerformed

    private void LoginButSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButSignActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
            dispose();
    }//GEN-LAST:event_LoginButSignActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnswerSign;
    private javax.swing.JLabel Emailsign;
    private javax.swing.JTextField Emailtxt;
    private javax.swing.JButton ExitButSign;
    private javax.swing.JButton LoginButSign;
    private javax.swing.JLabel NameSign;
    private javax.swing.JTextField Nametxt;
    private javax.swing.JLabel PasswordSign;
    private javax.swing.JButton SaveButSign;
    private javax.swing.JLabel SecuritySign;
    private javax.swing.JLabel USNsign;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPasswordField passwordtxt1;
    private javax.swing.JTextField phonetxt;
    private javax.swing.JTextField usntxt;
    // End of variables declaration//GEN-END:variables
}
